/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LaporanMutasi2017;

import com.mysql.jdbc.Connection;
import gudang.clas.DatabaseConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fauzan13
 */
public class Triwulan2 extends javax.swing.JFrame {

    /**
     * Creates new form Triwulan2
     */
    Connection koneksi;
    public Triwulan2() {
        initComponents();
                    setExtendedState(JFrame.MAXIMIZED_BOTH);
        koneksi = (Connection) DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_gudang_dishub");
        showDataATK();

    }
          DefaultTableModel dtm;

    public void showDataATK() {

        String[] kolom = {"NO", "NAMA BARANG", "VOLUME", "HARGA", "JUMLAH", "PENERIMAAN", "PENGELUARAN", "SISA", "HARGA", "JUMLAH"};

        dtm = new DefaultTableModel(null, kolom);

        try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT t_persediaan.nama_barang,t_persediaan.jumlah,t_bmasuk.harga,(t_bmasuk.harga*t_bmasuk.jumlah_masuk) as total,"
                    + "t_bmasuk.jumlah_masuk2,(t_transaksi.keluar) as pengeluaran,sum(t_persediaan.jumlah-t_transaksi.keluar)as ee " 
                    + "   FROM t_bmasuk,t_persediaan,t_transaksi "
                    + " WHERE t_transaksi.kode_barang=t_bmasuk.kode_barang and t_transaksi.kode_barang = t_persediaan.kode_barang "
                    + "and  t_transaksi.tanggal BETWEEN '2017-01-1' AND '2017-06-30'"
                    + "GROUP BY t_transaksi.triwulan ";
//,sum(t_transaksi.keluar) as pengeluaran   
            ResultSet rs = stmt.executeQuery(query);
            int no = 1;
            while (rs.next()) {

                String nama = rs.getString("nama_barang");
                String kd = rs.getString("jumlah");
                String kd1 = rs.getString("harga");
                String keluar = rs.getString("total")                       ;
                String keluar1 = rs.getString("pengeluaran");
                String pemasukan = rs.getString("jumlah_masuk2");
                String sisa = rs.getString("ee");
                
                dtm.addRow(new String[]{no + "", nama, kd, kd1, keluar,pemasukan,keluar1,sisa});
                no++;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        tblATK.setModel(dtm);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblATK = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListrik = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblKebersihan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCetakan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("DINAS PERHUBUNGAN KOTA BANDUNG");

        tblATK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "NAMA BARANG", "VOLUME", "HARGA", "JUMLAH", "PENERIMAAN", "PENGELUARAN", "SISA", "HARGA", "JUMLAH"
            }
        ));
        jScrollPane2.setViewportView(tblATK);

        tblListrik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "NAMA BARANG", "VOLUME", "HARGA", "JUMLAH", "PENERIMAAN", "PENGELUARAN", "SISA", "HARGA", "JUMLAH"
            }
        ));
        jScrollPane1.setViewportView(tblListrik);

        jLabel3.setText("TRIWULAN II");

        tblKebersihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "NAMA BARANG", "VOLUME", "HARGA", "JUMLAH", "PENERIMAAN", "PENGELUARAN", "SISA", "HARGA", "JUMLAH"
            }
        ));
        jScrollPane4.setViewportView(tblKebersihan);

        jLabel1.setText("LAPORAN MUTASI PERSEDIAAN");

        tblCetakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "NAMA BARANG", "VOLUME", "HARGA", "JUMLAH", "PENERIMAAN", "PENGELUARAN", "SISA", "HARGA", "JUMLAH"
            }
        ));
        jScrollPane3.setViewportView(tblCetakan);

        jLabel7.setText("CETAKAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(264, 264, 264)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(293, 293, 293)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(jLabel3)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addGap(44, 44, 44)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(47, 47, 47)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triwulan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triwulan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triwulan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triwulan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triwulan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblATK;
    private javax.swing.JTable tblCetakan;
    private javax.swing.JTable tblKebersihan;
    private javax.swing.JTable tblListrik;
    // End of variables declaration//GEN-END:variables
}
